services:
  nginx:
    ports:
      - "443:443"
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    env_file:
      - path: .env.nginx
        required: true
    environment:
      - DOMAIN=utrgv-finance-agent.alshival.cloud
      - NGINX_PROXY_CONNECT_TIMEOUT=${NGINX_PROXY_CONNECT_TIMEOUT:-300}
      - NGINX_PROXY_SEND_TIMEOUT=${NGINX_PROXY_SEND_TIMEOUT:-300}
      - NGINX_PROXY_READ_TIMEOUT=${NGINX_PROXY_READ_TIMEOUT:-300}
    command: >
      /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf
      && cp -a /nginx-templates/. /etc/nginx/conf.d/
      && sed 's/\r$//' /etc/nginx/conf.d/run-nginx.sh > /tmp/run-nginx.sh
      && chmod +x /tmp/run-nginx.sh
      && /tmp/run-nginx.sh app.conf.template.prod"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
